{"name": "Проверка сообщения об ошибке при неверных данных для логина", "status": "passed", "steps": [{"name": "Отправка запроса", "status": "passed", "parameters": [{"name": "method", "value": "'POST'"}, {"name": "endpoint", "value": "'/auth/login'"}, {"name": "json", "value": "{'email': 'invalid_user@example.com', 'password': 'wrongpassword'}"}], "start": 1737273836012, "stop": 1737273836150}], "start": 1737273836011, "stop": 1737273836151, "uuid": "e253ba4d-40a2-44bd-8ab7-d9fc3ca7fe27", "historyId": "e5774e472c142069bc9e66e164938d26", "testCaseId": "e5774e472c142069bc9e66e164938d26", "fullName": "tests.test_login_user.TestUserLogin#test_login_invalid_credentials_error_message", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "SergeiBazhenov"}, {"name": "thread", "value": "12572-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}