{"name": "Проверка сообщения об ошибке при обновлении имени пользователя без авторизации", "status": "passed", "steps": [{"name": "Отправка запроса", "status": "passed", "parameters": [{"name": "method", "value": "'PATCH'"}, {"name": "endpoint", "value": "'/auth/user'"}, {"name": "json", "value": "{'name': 'New Name'}"}], "start": 1737273839211, "stop": 1737273839357}], "start": 1737273839210, "stop": 1737273839358, "uuid": "54f89a76-7129-4e48-95f7-e0e7972820e7", "historyId": "d4690864e326be8520d37101b1620d87", "testCaseId": "d4690864e326be8520d37101b1620d87", "fullName": "tests.test_update_user_data.TestUserUpdate#test_update_user_without_auth_name_error_message", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_update_user_data"}, {"name": "subSuite", "value": "TestUserUpdate"}, {"name": "host", "value": "SergeiBazhenov"}, {"name": "thread", "value": "12572-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_update_user_data"}]}